//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiceAdmRural.wsEmail {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoemailSoap", Namespace="http://tempuri.org/")]
    public partial class Servicoemail : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MandaMensagemOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificaCercaOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificaCoordenadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultoDistanciaViaturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailFicaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailVisaDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailDetranCEOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailDetranDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailDERDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailDetranGOOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailMOPOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailAmcOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailCepromatOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailCasinhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailStransOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailSttramOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailProntoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailCbdOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailSemadOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailMopCidadaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servicoemail() {
            this.Url = global::ServiceAdmRural.Properties.Settings.Default.ServiceEcupom_wsEmail_Servicoemail;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MandaMensagemCompletedEventHandler MandaMensagemCompleted;
        
        /// <remarks/>
        public event VerificaCercaCompletedEventHandler VerificaCercaCompleted;
        
        /// <remarks/>
        public event VerificaCoordenadasCompletedEventHandler VerificaCoordenadasCompleted;
        
        /// <remarks/>
        public event ConsultoDistanciaViaturaCompletedEventHandler ConsultoDistanciaViaturaCompleted;
        
        /// <remarks/>
        public event EmailFicaiCompletedEventHandler EmailFicaiCompleted;
        
        /// <remarks/>
        public event EmailVisaDFCompletedEventHandler EmailVisaDFCompleted;
        
        /// <remarks/>
        public event EmailDetranCECompletedEventHandler EmailDetranCECompleted;
        
        /// <remarks/>
        public event EmailDetranDFCompletedEventHandler EmailDetranDFCompleted;
        
        /// <remarks/>
        public event EmailDERDFCompletedEventHandler EmailDERDFCompleted;
        
        /// <remarks/>
        public event EmailDetranGOCompletedEventHandler EmailDetranGOCompleted;
        
        /// <remarks/>
        public event EmailMOPCompletedEventHandler EmailMOPCompleted;
        
        /// <remarks/>
        public event EmailAmcCompletedEventHandler EmailAmcCompleted;
        
        /// <remarks/>
        public event EmailCepromatCompletedEventHandler EmailCepromatCompleted;
        
        /// <remarks/>
        public event EmailCasinhaCompletedEventHandler EmailCasinhaCompleted;
        
        /// <remarks/>
        public event EmailStransCompletedEventHandler EmailStransCompleted;
        
        /// <remarks/>
        public event EmailSttramCompletedEventHandler EmailSttramCompleted;
        
        /// <remarks/>
        public event EmailMenuCompletedEventHandler EmailMenuCompleted;
        
        /// <remarks/>
        public event EmailProntoCompletedEventHandler EmailProntoCompleted;
        
        /// <remarks/>
        public event EmailCbdCompletedEventHandler EmailCbdCompleted;
        
        /// <remarks/>
        public event EmailSemadCompletedEventHandler EmailSemadCompleted;
        
        /// <remarks/>
        public event EmailAnimalCompletedEventHandler EmailAnimalCompleted;
        
        /// <remarks/>
        public event EmailMopCidadaoCompletedEventHandler EmailMopCidadaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MandaMensagem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MandaMensagem(string email_origem, string nome_origem, string email_destino, string sujeito, string mensagem) {
            object[] results = this.Invoke("MandaMensagem", new object[] {
                        email_origem,
                        nome_origem,
                        email_destino,
                        sujeito,
                        mensagem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MandaMensagemAsync(string email_origem, string nome_origem, string email_destino, string sujeito, string mensagem) {
            this.MandaMensagemAsync(email_origem, nome_origem, email_destino, sujeito, mensagem, null);
        }
        
        /// <remarks/>
        public void MandaMensagemAsync(string email_origem, string nome_origem, string email_destino, string sujeito, string mensagem, object userState) {
            if ((this.MandaMensagemOperationCompleted == null)) {
                this.MandaMensagemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMandaMensagemOperationCompleted);
            }
            this.InvokeAsync("MandaMensagem", new object[] {
                        email_origem,
                        nome_origem,
                        email_destino,
                        sujeito,
                        mensagem}, this.MandaMensagemOperationCompleted, userState);
        }
        
        private void OnMandaMensagemOperationCompleted(object arg) {
            if ((this.MandaMensagemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MandaMensagemCompleted(this, new MandaMensagemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificaCerca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificaCerca(string usuario, string cerca) {
            object[] results = this.Invoke("VerificaCerca", new object[] {
                        usuario,
                        cerca});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerificaCercaAsync(string usuario, string cerca) {
            this.VerificaCercaAsync(usuario, cerca, null);
        }
        
        /// <remarks/>
        public void VerificaCercaAsync(string usuario, string cerca, object userState) {
            if ((this.VerificaCercaOperationCompleted == null)) {
                this.VerificaCercaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificaCercaOperationCompleted);
            }
            this.InvokeAsync("VerificaCerca", new object[] {
                        usuario,
                        cerca}, this.VerificaCercaOperationCompleted, userState);
        }
        
        private void OnVerificaCercaOperationCompleted(object arg) {
            if ((this.VerificaCercaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificaCercaCompleted(this, new VerificaCercaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificaCoordenadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificaCoordenadas(string latitude, string longitude) {
            object[] results = this.Invoke("VerificaCoordenadas", new object[] {
                        latitude,
                        longitude});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerificaCoordenadasAsync(string latitude, string longitude) {
            this.VerificaCoordenadasAsync(latitude, longitude, null);
        }
        
        /// <remarks/>
        public void VerificaCoordenadasAsync(string latitude, string longitude, object userState) {
            if ((this.VerificaCoordenadasOperationCompleted == null)) {
                this.VerificaCoordenadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificaCoordenadasOperationCompleted);
            }
            this.InvokeAsync("VerificaCoordenadas", new object[] {
                        latitude,
                        longitude}, this.VerificaCoordenadasOperationCompleted, userState);
        }
        
        private void OnVerificaCoordenadasOperationCompleted(object arg) {
            if ((this.VerificaCoordenadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificaCoordenadasCompleted(this, new VerificaCoordenadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultoDistanciaViatura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultoDistanciaViatura(string latitude1, string longitude1, string latitude2, string longitude2) {
            object[] results = this.Invoke("ConsultoDistanciaViatura", new object[] {
                        latitude1,
                        longitude1,
                        latitude2,
                        longitude2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultoDistanciaViaturaAsync(string latitude1, string longitude1, string latitude2, string longitude2) {
            this.ConsultoDistanciaViaturaAsync(latitude1, longitude1, latitude2, longitude2, null);
        }
        
        /// <remarks/>
        public void ConsultoDistanciaViaturaAsync(string latitude1, string longitude1, string latitude2, string longitude2, object userState) {
            if ((this.ConsultoDistanciaViaturaOperationCompleted == null)) {
                this.ConsultoDistanciaViaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultoDistanciaViaturaOperationCompleted);
            }
            this.InvokeAsync("ConsultoDistanciaViatura", new object[] {
                        latitude1,
                        longitude1,
                        latitude2,
                        longitude2}, this.ConsultoDistanciaViaturaOperationCompleted, userState);
        }
        
        private void OnConsultoDistanciaViaturaOperationCompleted(object arg) {
            if ((this.ConsultoDistanciaViaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultoDistanciaViaturaCompleted(this, new ConsultoDistanciaViaturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailFicai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailFicai(string email, string login, string senha) {
            object[] results = this.Invoke("EmailFicai", new object[] {
                        email,
                        login,
                        senha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailFicaiAsync(string email, string login, string senha) {
            this.EmailFicaiAsync(email, login, senha, null);
        }
        
        /// <remarks/>
        public void EmailFicaiAsync(string email, string login, string senha, object userState) {
            if ((this.EmailFicaiOperationCompleted == null)) {
                this.EmailFicaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailFicaiOperationCompleted);
            }
            this.InvokeAsync("EmailFicai", new object[] {
                        email,
                        login,
                        senha}, this.EmailFicaiOperationCompleted, userState);
        }
        
        private void OnEmailFicaiOperationCompleted(object arg) {
            if ((this.EmailFicaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailFicaiCompleted(this, new EmailFicaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailVisaDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailVisaDF(string email, string relatorio, string fantasia) {
            object[] results = this.Invoke("EmailVisaDF", new object[] {
                        email,
                        relatorio,
                        fantasia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailVisaDFAsync(string email, string relatorio, string fantasia) {
            this.EmailVisaDFAsync(email, relatorio, fantasia, null);
        }
        
        /// <remarks/>
        public void EmailVisaDFAsync(string email, string relatorio, string fantasia, object userState) {
            if ((this.EmailVisaDFOperationCompleted == null)) {
                this.EmailVisaDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailVisaDFOperationCompleted);
            }
            this.InvokeAsync("EmailVisaDF", new object[] {
                        email,
                        relatorio,
                        fantasia}, this.EmailVisaDFOperationCompleted, userState);
        }
        
        private void OnEmailVisaDFOperationCompleted(object arg) {
            if ((this.EmailVisaDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailVisaDFCompleted(this, new EmailVisaDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailDetranCE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailDetranCE(string email, string relatorio) {
            object[] results = this.Invoke("EmailDetranCE", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailDetranCEAsync(string email, string relatorio) {
            this.EmailDetranCEAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailDetranCEAsync(string email, string relatorio, object userState) {
            if ((this.EmailDetranCEOperationCompleted == null)) {
                this.EmailDetranCEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailDetranCEOperationCompleted);
            }
            this.InvokeAsync("EmailDetranCE", new object[] {
                        email,
                        relatorio}, this.EmailDetranCEOperationCompleted, userState);
        }
        
        private void OnEmailDetranCEOperationCompleted(object arg) {
            if ((this.EmailDetranCECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailDetranCECompleted(this, new EmailDetranCECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailDetranDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailDetranDF(string email, string relatorio) {
            object[] results = this.Invoke("EmailDetranDF", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailDetranDFAsync(string email, string relatorio) {
            this.EmailDetranDFAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailDetranDFAsync(string email, string relatorio, object userState) {
            if ((this.EmailDetranDFOperationCompleted == null)) {
                this.EmailDetranDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailDetranDFOperationCompleted);
            }
            this.InvokeAsync("EmailDetranDF", new object[] {
                        email,
                        relatorio}, this.EmailDetranDFOperationCompleted, userState);
        }
        
        private void OnEmailDetranDFOperationCompleted(object arg) {
            if ((this.EmailDetranDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailDetranDFCompleted(this, new EmailDetranDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailDERDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailDERDF(string email, string relatorio) {
            object[] results = this.Invoke("EmailDERDF", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailDERDFAsync(string email, string relatorio) {
            this.EmailDERDFAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailDERDFAsync(string email, string relatorio, object userState) {
            if ((this.EmailDERDFOperationCompleted == null)) {
                this.EmailDERDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailDERDFOperationCompleted);
            }
            this.InvokeAsync("EmailDERDF", new object[] {
                        email,
                        relatorio}, this.EmailDERDFOperationCompleted, userState);
        }
        
        private void OnEmailDERDFOperationCompleted(object arg) {
            if ((this.EmailDERDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailDERDFCompleted(this, new EmailDERDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailDetranGO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailDetranGO(string email, string relatorio) {
            object[] results = this.Invoke("EmailDetranGO", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailDetranGOAsync(string email, string relatorio) {
            this.EmailDetranGOAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailDetranGOAsync(string email, string relatorio, object userState) {
            if ((this.EmailDetranGOOperationCompleted == null)) {
                this.EmailDetranGOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailDetranGOOperationCompleted);
            }
            this.InvokeAsync("EmailDetranGO", new object[] {
                        email,
                        relatorio}, this.EmailDetranGOOperationCompleted, userState);
        }
        
        private void OnEmailDetranGOOperationCompleted(object arg) {
            if ((this.EmailDetranGOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailDetranGOCompleted(this, new EmailDetranGOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailMOP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailMOP(string email, string relatorio) {
            object[] results = this.Invoke("EmailMOP", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailMOPAsync(string email, string relatorio) {
            this.EmailMOPAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailMOPAsync(string email, string relatorio, object userState) {
            if ((this.EmailMOPOperationCompleted == null)) {
                this.EmailMOPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailMOPOperationCompleted);
            }
            this.InvokeAsync("EmailMOP", new object[] {
                        email,
                        relatorio}, this.EmailMOPOperationCompleted, userState);
        }
        
        private void OnEmailMOPOperationCompleted(object arg) {
            if ((this.EmailMOPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailMOPCompleted(this, new EmailMOPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailAmc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailAmc(string email, string relatorio) {
            object[] results = this.Invoke("EmailAmc", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailAmcAsync(string email, string relatorio) {
            this.EmailAmcAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailAmcAsync(string email, string relatorio, object userState) {
            if ((this.EmailAmcOperationCompleted == null)) {
                this.EmailAmcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailAmcOperationCompleted);
            }
            this.InvokeAsync("EmailAmc", new object[] {
                        email,
                        relatorio}, this.EmailAmcOperationCompleted, userState);
        }
        
        private void OnEmailAmcOperationCompleted(object arg) {
            if ((this.EmailAmcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailAmcCompleted(this, new EmailAmcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailCepromat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailCepromat(string email, string relatorio) {
            object[] results = this.Invoke("EmailCepromat", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailCepromatAsync(string email, string relatorio) {
            this.EmailCepromatAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailCepromatAsync(string email, string relatorio, object userState) {
            if ((this.EmailCepromatOperationCompleted == null)) {
                this.EmailCepromatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailCepromatOperationCompleted);
            }
            this.InvokeAsync("EmailCepromat", new object[] {
                        email,
                        relatorio}, this.EmailCepromatOperationCompleted, userState);
        }
        
        private void OnEmailCepromatOperationCompleted(object arg) {
            if ((this.EmailCepromatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailCepromatCompleted(this, new EmailCepromatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailCasinha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailCasinha(string email, string relatorio, string body) {
            object[] results = this.Invoke("EmailCasinha", new object[] {
                        email,
                        relatorio,
                        body});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailCasinhaAsync(string email, string relatorio, string body) {
            this.EmailCasinhaAsync(email, relatorio, body, null);
        }
        
        /// <remarks/>
        public void EmailCasinhaAsync(string email, string relatorio, string body, object userState) {
            if ((this.EmailCasinhaOperationCompleted == null)) {
                this.EmailCasinhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailCasinhaOperationCompleted);
            }
            this.InvokeAsync("EmailCasinha", new object[] {
                        email,
                        relatorio,
                        body}, this.EmailCasinhaOperationCompleted, userState);
        }
        
        private void OnEmailCasinhaOperationCompleted(object arg) {
            if ((this.EmailCasinhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailCasinhaCompleted(this, new EmailCasinhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailStrans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailStrans(string email, string relatorio) {
            object[] results = this.Invoke("EmailStrans", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailStransAsync(string email, string relatorio) {
            this.EmailStransAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailStransAsync(string email, string relatorio, object userState) {
            if ((this.EmailStransOperationCompleted == null)) {
                this.EmailStransOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailStransOperationCompleted);
            }
            this.InvokeAsync("EmailStrans", new object[] {
                        email,
                        relatorio}, this.EmailStransOperationCompleted, userState);
        }
        
        private void OnEmailStransOperationCompleted(object arg) {
            if ((this.EmailStransCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailStransCompleted(this, new EmailStransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailSttram", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailSttram(string email, string relatorio) {
            object[] results = this.Invoke("EmailSttram", new object[] {
                        email,
                        relatorio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailSttramAsync(string email, string relatorio) {
            this.EmailSttramAsync(email, relatorio, null);
        }
        
        /// <remarks/>
        public void EmailSttramAsync(string email, string relatorio, object userState) {
            if ((this.EmailSttramOperationCompleted == null)) {
                this.EmailSttramOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailSttramOperationCompleted);
            }
            this.InvokeAsync("EmailSttram", new object[] {
                        email,
                        relatorio}, this.EmailSttramOperationCompleted, userState);
        }
        
        private void OnEmailSttramOperationCompleted(object arg) {
            if ((this.EmailSttramCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailSttramCompleted(this, new EmailSttramCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailMenu(string email, string body) {
            object[] results = this.Invoke("EmailMenu", new object[] {
                        email,
                        body});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailMenuAsync(string email, string body) {
            this.EmailMenuAsync(email, body, null);
        }
        
        /// <remarks/>
        public void EmailMenuAsync(string email, string body, object userState) {
            if ((this.EmailMenuOperationCompleted == null)) {
                this.EmailMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailMenuOperationCompleted);
            }
            this.InvokeAsync("EmailMenu", new object[] {
                        email,
                        body}, this.EmailMenuOperationCompleted, userState);
        }
        
        private void OnEmailMenuOperationCompleted(object arg) {
            if ((this.EmailMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailMenuCompleted(this, new EmailMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailPronto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailPronto(string email, string body) {
            object[] results = this.Invoke("EmailPronto", new object[] {
                        email,
                        body});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailProntoAsync(string email, string body) {
            this.EmailProntoAsync(email, body, null);
        }
        
        /// <remarks/>
        public void EmailProntoAsync(string email, string body, object userState) {
            if ((this.EmailProntoOperationCompleted == null)) {
                this.EmailProntoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailProntoOperationCompleted);
            }
            this.InvokeAsync("EmailPronto", new object[] {
                        email,
                        body}, this.EmailProntoOperationCompleted, userState);
        }
        
        private void OnEmailProntoOperationCompleted(object arg) {
            if ((this.EmailProntoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailProntoCompleted(this, new EmailProntoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailCbd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailCbd(string email, string body) {
            object[] results = this.Invoke("EmailCbd", new object[] {
                        email,
                        body});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailCbdAsync(string email, string body) {
            this.EmailCbdAsync(email, body, null);
        }
        
        /// <remarks/>
        public void EmailCbdAsync(string email, string body, object userState) {
            if ((this.EmailCbdOperationCompleted == null)) {
                this.EmailCbdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailCbdOperationCompleted);
            }
            this.InvokeAsync("EmailCbd", new object[] {
                        email,
                        body}, this.EmailCbdOperationCompleted, userState);
        }
        
        private void OnEmailCbdOperationCompleted(object arg) {
            if ((this.EmailCbdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailCbdCompleted(this, new EmailCbdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailSemad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailSemad(string email, string body) {
            object[] results = this.Invoke("EmailSemad", new object[] {
                        email,
                        body});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailSemadAsync(string email, string body) {
            this.EmailSemadAsync(email, body, null);
        }
        
        /// <remarks/>
        public void EmailSemadAsync(string email, string body, object userState) {
            if ((this.EmailSemadOperationCompleted == null)) {
                this.EmailSemadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailSemadOperationCompleted);
            }
            this.InvokeAsync("EmailSemad", new object[] {
                        email,
                        body}, this.EmailSemadOperationCompleted, userState);
        }
        
        private void OnEmailSemadOperationCompleted(object arg) {
            if ((this.EmailSemadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailSemadCompleted(this, new EmailSemadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailAnimal(string email, string body) {
            object[] results = this.Invoke("EmailAnimal", new object[] {
                        email,
                        body});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailAnimalAsync(string email, string body) {
            this.EmailAnimalAsync(email, body, null);
        }
        
        /// <remarks/>
        public void EmailAnimalAsync(string email, string body, object userState) {
            if ((this.EmailAnimalOperationCompleted == null)) {
                this.EmailAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailAnimalOperationCompleted);
            }
            this.InvokeAsync("EmailAnimal", new object[] {
                        email,
                        body}, this.EmailAnimalOperationCompleted, userState);
        }
        
        private void OnEmailAnimalOperationCompleted(object arg) {
            if ((this.EmailAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailAnimalCompleted(this, new EmailAnimalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmailMopCidadao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EmailMopCidadao(string email, string body) {
            object[] results = this.Invoke("EmailMopCidadao", new object[] {
                        email,
                        body});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmailMopCidadaoAsync(string email, string body) {
            this.EmailMopCidadaoAsync(email, body, null);
        }
        
        /// <remarks/>
        public void EmailMopCidadaoAsync(string email, string body, object userState) {
            if ((this.EmailMopCidadaoOperationCompleted == null)) {
                this.EmailMopCidadaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailMopCidadaoOperationCompleted);
            }
            this.InvokeAsync("EmailMopCidadao", new object[] {
                        email,
                        body}, this.EmailMopCidadaoOperationCompleted, userState);
        }
        
        private void OnEmailMopCidadaoOperationCompleted(object arg) {
            if ((this.EmailMopCidadaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailMopCidadaoCompleted(this, new EmailMopCidadaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MandaMensagemCompletedEventHandler(object sender, MandaMensagemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MandaMensagemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MandaMensagemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void VerificaCercaCompletedEventHandler(object sender, VerificaCercaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificaCercaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificaCercaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void VerificaCoordenadasCompletedEventHandler(object sender, VerificaCoordenadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificaCoordenadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificaCoordenadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultoDistanciaViaturaCompletedEventHandler(object sender, ConsultoDistanciaViaturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultoDistanciaViaturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultoDistanciaViaturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailFicaiCompletedEventHandler(object sender, EmailFicaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailFicaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailFicaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailVisaDFCompletedEventHandler(object sender, EmailVisaDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailVisaDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailVisaDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailDetranCECompletedEventHandler(object sender, EmailDetranCECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailDetranCECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailDetranCECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailDetranDFCompletedEventHandler(object sender, EmailDetranDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailDetranDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailDetranDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailDERDFCompletedEventHandler(object sender, EmailDERDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailDERDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailDERDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailDetranGOCompletedEventHandler(object sender, EmailDetranGOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailDetranGOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailDetranGOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailMOPCompletedEventHandler(object sender, EmailMOPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailMOPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailMOPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailAmcCompletedEventHandler(object sender, EmailAmcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailAmcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailAmcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailCepromatCompletedEventHandler(object sender, EmailCepromatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailCepromatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailCepromatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailCasinhaCompletedEventHandler(object sender, EmailCasinhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailCasinhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailCasinhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailStransCompletedEventHandler(object sender, EmailStransCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailStransCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailStransCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailSttramCompletedEventHandler(object sender, EmailSttramCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailSttramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailSttramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailMenuCompletedEventHandler(object sender, EmailMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailProntoCompletedEventHandler(object sender, EmailProntoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailProntoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailProntoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailCbdCompletedEventHandler(object sender, EmailCbdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailCbdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailCbdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailSemadCompletedEventHandler(object sender, EmailSemadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailSemadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailSemadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailAnimalCompletedEventHandler(object sender, EmailAnimalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailAnimalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailAnimalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EmailMopCidadaoCompletedEventHandler(object sender, EmailMopCidadaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailMopCidadaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailMopCidadaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591